### ISSUE TITLE
medium .net exe not running when attaching to another process

### ISSUE THREAD

**Issue by waytoosexy** [TheWover/donut#114]
I have an executable that is around 2.7 MB when I run the DonutTest without any process it executes the exe, but when I give another Process ID it does not work. I have tried with multiple processes.

**Comment by TheWover** [comment]
This could be a number of issues such as incorrect process architectures, blocks by defenses, or something in the logic of the payload. I will close this issue for now. If you have more details you can post them here as a comment and reopen.
