### ISSUE TITLE
Suggestion on encoding the loader

### ISSUE THREAD

**Issue by CaledoniaProject** [TheWover/donut#138]
I'm wondering how [loader_exe_x64.h](https://github.com/TheWover/donut/blob/v1.0/loader_exe_x64.h) is generated and how can I encode/modify it. The loader is already flagged by multiple AV.

**Comment by TheWover** [comment]
Check out the Makefiles to see how it is built. Basically, it is compiled when you run make and exe2h is used on loader.exe to generate the header files. If you want to encode/modify it then you would either need to modify the source code of the loader, integrate obfuscation into the compilation process, or encode it after it it is already generated.
