### ISSUE TITLE
Files with SEH support 

### ISSUE THREAD

**Issue by rashik671games** [TheWover/donut#143]
Any ideas how to add support to files with SEH? 
For x64 unmanaged binaries we can use RtlAddFunctionTable NTAPI, but what about x32 binaries?

**Comment by upsground** [comment]
It didn't work for me. When my c++ application throws an exception, the program just crashes.

I generate as follows: ```
donut.exe -a:2 -j:in.exe -i:in.exe
```

What am I doing wrong?

**Comment by upsground** [comment]
It didn't work for me. When my c++ application throws an exception, the program just crashes.

I generate as follows: donut.exe -a:2 -j:in.exe -i:in.exe

What am I doing wrong?
