### ISSUE TITLE
commandline issues with unamanaged exe compiled with vs2019 

### ISSUE THREAD

**Issue by antonioCoco** [TheWover/donut#18]
Hi @odzhan ,
recently i found some issues in the master branch for the commandline of exe compiled with vs2019 gui.

Using the following sample as an exe program:

```
#include <stdio.h>

int wmain (int argc, wchar_t **argv)
{
    wprintf(L"\nHello from WMAIN\n");
    wprintf(L"\nArgc: %d\n", argc);
    for(int i=0; i<argc; i++)
        wprintf(L"\nArgv[%d]: %s\n", i, argv[i]);
    wprintf(L"\nWMAIN End. BB!\n");
    return 0;
}
```

If you compile that in x64 default release from the gui it will generate a different exe with different import than the usual __getmainargs/__wgetmainargs and GetCommandLineA/GetCommandLineW.
If i try to generate the PIC of this exe i won't get the correct commandline passed to the main.

I dig into it and found out the flags used by the gui for the compiler and they are as follow:

```
cl /c /Zi /nologo /W3 /WX- /diagnostics:column /sdl /O2 /Oi /GL /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /Gd /TC /FC C:\USERS\SPLINTERCODE\SOURCE\REPOS\TEST_DONUT_MAIN\TEST_DONUT_MAIN.C

link /OUT:"TEST_DONUT_MAIN.EXE" /INCREMENTAL:NO /NOLOGO KERNEL32.LIB USER32.LIB GDI32.LIB WINSPOOL.LIB COMDLG32.LIB ADVAPI32.LIB SHELL32.LIB OLE32.LIB OLEAUT32.LIB UUID.LIB ODBC32.LIB ODBCCP32.LIB /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /MACHINE:X64 TEST_DONUT_MAIN.OBJ
```

I couldn't found anything "strange" in the flags. The only unusual thing i noticed was in the imported functions of the exe, i saw : "__p___argc", "__p___argv" and "__p___wargv" imported in the exe.
Hooking those functions fixed this issue and i could see the commandline arguments parsed as expected in the final PIC.
I made this change in  antonioCoco/donut@ec105faa92f573e892f669ebcdfbfd5c0ac1dfc8 and i managed to fix this issue in my hook branch. Soon i will submit a PR in order to merge with the main hook branch.

Unfortunately i couldn't find a fix by just patching .data section for the master branch version.

Attached the compiled exe:
[TEST_DONUT_MAIN.zip](https://github.com/TheWover/donut/files/3772611/TEST_DONUT_MAIN.zip)

**Comment by odzhan** [comment]
Hey. :) There are a bunch of symbols exported by ucrtbase.dll like msvcrt.dll and these can be patched in similar way to modify the command line. I'm not against hooking at all, but we want to use code stubs written in C rather than assembly and potentially have a way to restore code modified after execution. Donut can't do this now without a disassembler to count the number of bytes to move. Although the symbols in ucrtbase.dll can be modified in the same way msvcrt.dll is, I can see this is getting tedious now. Thanks for the report and demo code.

**Comment by antonioCoco** [comment]
> Hey. :) There are a bunch of symbols exported by ucrtbase.dll like msvcrt.dll and these can be patched in similar way to modify the command line. I'm not against hooking at all, but we want to use code stubs written in C rather than assembly and potentially have a way to restore code modified after execution. Donut can't do this now without a disassembler to count the number of bytes to save/restore. Although the symbols in ucrtbase.dll can be modified in the same way msvcrt.dll is, I can see this is getting tedious now. Thanks for the report and demo code.

Totally agree on writing c code stubs for hooking.
What i just saw in patching data section is that you have to travel all the heaps everytime you need to patch some data. This could add so much runtime overhead on processes with large heaps.
Adding hooks needs more testing and debug from a dev perspective but it doesn't affect runtime performances like patching data sections. This made hooking also more scalable because you add almost no overhead for each new hooks you place.

Another thing i noticed is that patching .data sections will affect also the host process for the PIC while hooking will affect only the local scope of the PIC thread. This can make difference if you decide to inject in critical system processes.

About restoring code i don't think you need to restore the whole code but just the pointer changed in IAT. Anyway the IAT of the host process is not touched at all so i would skip any iat restoring. Only the internal IAT of the injected PIC would be affected by those hooks. This could be proven by a multithreaded exe that uses some shared syscall and observing the behaviour after the PIC gets injected.

All those feedbacks comes because i'm heavily using this great tool in the last days :) Hopefully those feedbacks can help!

**Comment by odzhan** [comment]
Apologies for the late response about this. Just hadn't time to look at it in any great detail. Although somewhat messy and probably not a full proof solution. If the symbols _acmdln, __argv, _wcmdln and __wargv are exported by a DLL in memory, they are patched with the new command line. Likewise, __p__acmdln, __p__argv, __p__wcmdln and __p__wargv that return pointers to those symbols are patched with the new command. For now, this addresses the problem and will close issue, but if you find any more, feel free to mention here.
