### ISSUE TITLE
[Feature] Update the Command Switches

### ISSUE THREAD

**Issue by am0nsec** [TheWover/donut#24]
This is definitely not an high priority issue, but updating the current command switches and parser would be a good idea.

At the moment, switches are only one char (e.g. "-n", "-a"). Therefore, command line switches are limited and are not really convenient. Additionally, some switches are a bit confusing, for example, the "-e" switch is used for the output format when this should be something like "-format".

Something like that, for example:
```c
printf("       -a, -arch<arch>            Target architecture : 1=x86, 2=amd64, 3=amd64+x86(default).\n");
printf("       -o, -out <outfile_file>    Default is \"loader.bin\"\n");
printf("       -format <format>          Output in the specified format. 1=raw (default), 2=base64, 3=c, 4=ruby, 5=python, 6=powershell, 7=C#, 8=hex\n");
```

**Comment by odzhan** [comment]
I have thought about this recently as more options are added. The switches will be updated at some point before v1.0.
