### ISSUE TITLE
Wipe MZ headers

### ISSUE THREAD

**Issue by TheWover** [TheWover/donut#25]
Wipe MZ and other unnecessary metadeta headers from memory before loading PEs. Perhaps the Rich headers, as well?

Memory scanners and EDR hooks look for the presence of these headers when attempting to detect signs of process injection. Removing these would bypass fragile detections.

**Comment by odzhan** [comment]
For the unmanaged PE files, it would be fine to remove https://github.com/TheWover/donut/blob/fa7e0ea06589beed85fadcc4007a2080901d9627/loader/inmem_pe.c#L110 from the loader. Not sure about .NET stuff as I think the CLR parses the PE headers.

**Comment by TheWover** [comment]
Yeah, I don't want to touch the .NET Assemblies. I think you're right about the CLR using the PE headers. Just want to wipe the headers in the unmanaged PEs that EDR and AV look for.

**Comment by odzhan** [comment]
Added some code to wipe DOS/PE headers from memory before execution. https://github.com/TheWover/donut/blob/fbed423b1c5d3cacfb03671d3adae02d64d528aa/loader/inmem_pe.c#L317
