### ISSUE TITLE
Sizing Issues

### ISSUE THREAD

**Issue by asaurusrex** [TheWover/donut#30]
I have used the exe version of donut on a 64-bit payload that was ~300K, and the produced bin file was ~33K and did not execute or act as expected

**Comment by odzhan** [comment]
Make a debug build of donut. Run it against the file you want to execute in-memory. Paste the output here. Also, what operating system are you running donut on?

**Comment by asaurusrex** [comment]
Tried with Release and Debug I'm pretty sure, and tried on Win10 and Kali Linux.  I will go back and get the output
