### ISSUE TITLE
compiling as python, Linux throwing an error 

### ISSUE THREAD

**Issue by Harikrish93** [TheWover/donut#63]
while running make command

gcc -Wall -fpack-struct=8 -DDONUT_EXE -I include donut.c hash.c encrypt.c payload/clib.c -odonut
In file included from include/pe.h:5,
                 from include/donut.h:57,
                 from donut.c:32:
include/wintypes.h:88: error: redefinition of typedef ‘CHAR’
include/wintypes.h:73: note: previous declaration of ‘CHAR’ was here
In file included from donut.c:32:
include/donut.h:82: error: redefinition of typedef ‘DWORD’
include/wintypes.h:57: note: previous declaration of ‘DWORD’ was here
include/donut.h:83: error: redefinition of typedef ‘WORD’
include/wintypes.h:49: note: previous declaration of ‘WORD’ was here
include/donut.h:84: error: redefinition of typedef ‘BYTE’
include/wintypes.h:37: note: previous declaration of ‘BYTE’ was here
include/donut.h:86: error: redefinition of typedef ‘CHAR’
include/wintypes.h:88: note: previous declaration of ‘CHAR’ was here
make: *** [donut] Error 1

Don't know how to fix this , please need help on this

**Comment by odzhan** [comment]
You must have changed the source code.
