### ISSUE TITLE
Sections are not mapped with the correct page protection

### ISSUE THREAD

**Issue by Dewera** [TheWover/donut#77]
I noticed that all section pages are mapped with RWX. Whilst this does 'work' for the most part, it would be better to apply the correct protection based on the characteristics of each section. Sections that require PAGE_NOCACHE and WRITECOPY variants would particularly benefit from this.

**Comment by TheWover** [comment]
Partially resolved in #38 and will be more completely resolved before next version.

**Comment by TheWover** [comment]
Fully resolved in dev, will be pushed with next version.

![image](https://user-images.githubusercontent.com/17090738/114744159-02b09b00-9d13-11eb-957d-fa5104172c7b.png)
